# Extensions
## Plugins: http://hexo.io/plugins/
## Themes: http://hexo.io/themes/
theme: polarbear
title: Joker
archive_generator:
    per_page: 0
    yearly: false
    monthly: false
    daily: false
# widget function
# false: disable
# widget_custom: custom your widget
#   title: your widget title
#   content: Add your html code in here. Example: <p>testing...</p>
widget:
  Tags: false
  Categories: true
  Custom: false

widget_custom:
    title: Test
    content: <p>testing...</p>
